Repository Quantco/slim-trees, pull requests merged in 2023-07, with the labels that each got.

#64 Switch to hatchling and pixi
  .github/workflows/benchmark.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .gitignore
  environment-deprecated.yml
  pixi.toml
  pyproject.toml
  setup.cfg
  slim_trees/__init__.py
  slim_trees/_version.py
Labels: ci, no benchmark

#67 Add pixi to installation instructions
  README.md
Labels: documentation

#69 Allow for custom unpickler in load(s)_compressed
  environment-deprecated.yml
  pixi.toml
  pyproject.toml
  slim_trees/pickling.py
  tests/test_lgbm_compression.py
  tests/test_sklearn_compression.py
Labels: enhancement

#74 Add support for sklearn 1.3.0
  .github/workflows/ci.yml
  environment-deprecated.yml
  pixi.toml
  pyproject.toml
  slim_trees/sklearn_tree.py
  tests/test_sklearn_compression.py
Labels: bug
